name: CICD
on:
  push:
    branches: [main]
jobs:
  build:
    name: build
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t brew3/fcw-server .
      - name: Publish image to docker hub
        run: docker push brew3/fcw-server:latest
