name: CICD
on:
  push:
    branches: [main]
jobs:
  build:
    name: build
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t brew3/fcw-server .
      - name: Publish image to docker hub
        run: docker push brew3/fcw-server:latest
  deploy:
    name: deploy
    needs: build
    runs-on: [server-runner]
    steps:
      - name: Pull latest image from docker hub
        run: docker pull brew3/fcw-server:latest
        working-directory: /app
      - name: Re-run docker compose
        run: docker-compose up -d
        working-directory: /app
      - name: Remove old image
        run: docker image prune -f
